name: Test API Key

on:
  push:
    branches: [ main ]

jobs:
  test-key:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Key is Available
        run: |
          if [ -n "${{ secrets.GEMINI_API_KEY }}" ]; then
            echo "✅ FOUND: The secret GEMINI_API_KEY exists!"
          else
            echo "❌ ERROR: The secret GEMINI_API_KEY was NOT found."
            exit 1
          fi
